### ISSUE TITLE
Beekeper

### ISSUE THREAD

**Issue by efinder2** [jetpack-maniac/autobee#3]
I'd like to write a Programm for beekeeping could you inform me how I can get the needed informations? 
I haven't found a  method for getting the meta data...

**Comment by jetpack-maniac** [comment]
I can point you in the right direction.  Methods for getting metadata will be via one of two mods.  Those mods are OpenPeripherals (1.7.10) and Plethora Peripherals (1.8+).  Without those mods you won't be able to use computers to move items within an apiary.

Plethora uses device.getItemMeta (see https://squiddev-cc.github.io/plethora/methods.html) 
OpenP uses device.getStackinSlot (OpenPeripherals uses in-game documentation only)
Where device is the wrapped device in ComputerCraft or the device address in OpenComputers.

**Comment by jetpack-maniac** [comment]
Also post on the computer mods forums, they will be able help more than I can.

[ComputerCraft](http://www.computercraft.info/forums2/)
[OpenComputers](https://oc.cil.li)
